source/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import ProjectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProjectView.as_view(), name='home_page'),
    path('account/', include('accounts.urls')),
    path('project/<p_pk>/tasks/', include('todo.urls')),
    path('projects/', include('projects.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from todo.views import (TaskStatusFilter, TaskDetailView, TaskCreateView,
                        TaskUpdateView, TaskDeleteView, TaskView)


urlpatterns = [
    path('list/', TaskView.as_view(), name='task_list'),
    path('status/<s_pk>/date/<filter>/user/<user_pk>/', TaskStatusFilter.as_view(), name='task_filter'),
    path('detail/<pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('update/<pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<pk>/', TaskDeleteView.as_view(), name='task_delete'),
]

projects/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Project(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    users = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Пользователь')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('project_detail', kwargs={
            'pk': self.pk
        })
    class Meta:
        permissions = [
            ('add_user_to_project', 'Can add user to project')
        ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>To Do list</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary mb-3" >
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home_page' %}">To Do List</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% block create %}
          {%endblock%}
          {% block filters_dropdown %}
          {%endblock%}
        </ul>
        <ul class="navbar-nav me-0 mb-2 mb-lg-0">
          {% block search %}
          {%endblock%}
          {% include 'partials/authentication_menu.html' %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="mx-3">
    {% block linkBack %}
    {% endblock %}
  </div>
  <div class="mb-3">
    {% block title %}
    {% endblock %}
  </div>
  <div class="row mx-3">
    <div class="col-md-3 d-none d-md-block">
      {% block filter %}
      {% endblock %}
    </div>
    <div class="col-md-6">
      {% block content %}
      {% endblock %}
    </div>
    <div class="col-md-3 d-none d-md-block">
      {% block usersblock %}
      {% endblock %}
    </div>
  </div>

  <footer class="bg-black">
    <section class="footer">
      <div class="container d-flex justify-content-center">
        <div>
            <h4 class="text-white">Мы в сети</h4>
            <div class="footer-icons d-flex justify-content-center mb-2">
              <a class="me-2 text-white" href=""><i class="fab fa-facebook-f"></i></a>
              <a class="me-2 text-white" href=""><i class="fab fa-youtube"></i></a>
              <a class="me-2 text-white" href=""><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </div>
    </section>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/c96917ab2e.js" crossorigin="anonymous"></script>
  {% block script%}
  {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  <h1 class="text-center">Список проектов:</h1>
{% endblock %}

{% block create %}
{% if perms.projects.add_project %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'project_create' %}"><i class="fa-solid fa-circle-plus"></i> Создать проект</a>
</li>
{%endif%}
{%endblock%}

{% block content %}

{% if request.GET.search %}
  {% include 'partials/pagination_search.html' %}
{%else%}
  {% include 'partials/pagination.html' %}
{%endif%}

{% for project in projects %}

<div class="card shadow mb-3">
  <div class="card-body">
    <h5 class="card-title">{{project.name}}</h5>

    <div class="d-flex justify-content-start">
      <p class="card-text me-2">Члены проекта: </p>
      {% for user in project.users.all %}
      <p class="card-text me-2">{{user}}{% if not forloop.last %}, {% endif %}</p>
      {% endfor %}
    </div>
    <p class="card-text"><small class="text-body-secondary">{{project.created_at}}</small></p>
    <a href="{% url 'project_detail' project.pk %}" class="btn btn-outline-primary"><i class="fa-regular fa-folder-open"></i> Открыть</a>
  </div>
</div>

{% endfor %}

{% if request.GET.search %}
  {% include 'partials/pagination_search.html' %}
{%else%}
  {% include 'partials/pagination.html' %}
{%endif%}

{% endblock %}
 