source/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import ProjectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProjectView.as_view(), name='home_page'),
    path('account/', include('accounts.urls')),
    path('project/<p_pk>/tasks/', include('todo.urls')),
    path('projects/', include('projects.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from todo.views import (TaskStatusFilter, TaskDetailView, TaskCreateView,
                        TaskUpdateView, TaskDeleteView, TaskView)


urlpatterns = [
    path('list/', TaskView.as_view(), name='task_list'),
    path('status/<s_pk>/date/<filter>/user/<user_pk>/', TaskStatusFilter.as_view(), name='task_filter'),
    path('detail/<pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('update/<pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<pk>/', TaskDeleteView.as_view(), name='task_delete'),
]

todo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from projects.models import Project

class Status(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Название')

    def __str__(self):
        return self.name

class Task(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    status = models.ForeignKey(to=Status, on_delete=models.CASCADE, null=False, related_name='tasks', verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    users = models.ManyToManyField(get_user_model(), related_name='tasks', blank=True, verbose_name='Пользователь')
    project = models.ForeignKey(to=Project, on_delete=models.CASCADE, null=True, blank=True, related_name='tasks', verbose_name='Проект')
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('task_detail', kwargs={
            'pk': self.pk
        })


# Create your models here.

templates/tasks/task_create.html
{% extends 'base.html' %}
{% block content %}


<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">Создать задачу по проекту:</h5>
        <h5>"{{project}}"</h5>
        <form action="{% url 'task_create' project.pk %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{% url 'task_list' project.pk %}" class="btn btn-outline-secondary mt-3"><i class="fa-solid fa-xmark"></i> Отмена</a>
            <button type="submit" class="btn btn-outline-primary mt-3"><i class="fa-solid fa-circle-check"></i> Создать</button>
        </form>
    </div>
  </div>
  

{% endblock %}

templates/tasks/task_delete.html
{% extends 'base.html' %}
{% block content %}


<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">Вы уверены что хотите удалить задачу "{{task}}"</h5>
        <form action="{% url 'task_delete' task.project.pk task.pk %}" method="POST">
            {% csrf_token %}
            <a href="{% url 'task_detail' task.project.pk task.pk %}" class="btn btn-outline-secondary mt-3"><i class="fa-solid fa-xmark"></i> Отмена</a>
            <button type="submit" class="btn btn-outline-primary mt-3"><i class="fa-solid fa-circle-check"></i> Удалить</button>
        </form>
    </div>
  </div>
  

{% endblock %}

templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block create %}
{% if perms.todo.add_task %}
{% if user in project.users.all %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'task_create' task.project.pk %}"><i class="fa-solid fa-circle-plus"></i> Создать задачу</a>
</li>
{%endif%}
{%endif%}
{%endblock%}

{% block linkBack %}
  <a class="icon-link icon-link-hover" href="{% url 'task_list' task.project.pk %}">
  <- Вернуться к списку задач
  <svg class="bi" aria-hidden="true"><use xlink:href="#arrow-right"></use></svg>
  </a>
{% endblock %}

{% block title %}
  <h1 class="text-center">Задача по проекту "{{task.project}}"</h1>
{% endblock %}

{% block content %}
<div class="card shadow mb-3">
  <div class="card-body">
    <h5 class="card-title">{{task.title}}</h5>
    {% include 'partials/task_status_color.html' %}
    <p class="card-text">{{task.description|linebreaks}}</p>
    <div class="d-flex justify-content-start">
      <p class="card-text me-2">Задача для: </p>
      {% for user in task.users.all %}
      <p class="card-text me-2">{{user}}{% if not forloop.last %}, {% endif %}</p>
      {% endfor %}
    </div>
    <p class="card-text"><small class="text-body-secondary">{{task.created_at}}</small></p>
    {% if user in task.users.all %}
    {% if perms.todo.change_task %}
    <a href="{% url 'task_update' task.project.pk task.pk %}" class="btn btn-outline-primary"><i class="fa-solid fa-pen-to-square"></i> Изменить</a>
    {%endif%}
    {% if perms.todo.delete_task %}
    <a href="{% url 'task_delete' task.project.pk task.pk %}" class="btn btn-outline-danger"><i class="fa-solid fa-trash-can"></i> Удалить</a>
    {%endif%}
    {%else%}
    <p class="card-text text-danger">Вы не не являетесь ответственным за эту задачу!</p>
    {%endif%}
  </div>
</div>
  

{% endblock %}

templates/tasks/task_list.html
{% extends 'base.html' %}
{% load static %}

{% block create %}
{% if perms.todo.add_task %}
{% if user in project.users.all %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'task_create' project.pk %}"><i class="fa-solid fa-circle-plus"></i> Создать задачу</a>
</li>
{%endif%}
{%endif%}
{%endblock%}

{% block filters_dropdown %}
  <li class="nav-item dropdown d-block d-md-none ">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Статус
    </a>
    <ul class="dropdown-menu">
      {% include 'partials/status_filter.html' with list_class="dropdown-item" %}
    </ul>
  </li>
  <li class="nav-item dropdown d-block d-md-none ">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Дата
    </a>
    <ul class="dropdown-menu">
      {% include 'partials/date_filter.html' with list_class="dropdown-item" %}
    </ul>
  </li>
{%endblock%}

{% block search %}
<li>
  <form class="d-flex" role="search" method="GET">
    <input class="form-control me-2" type="search" name="search" placeholder="Поиск" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Поиск</button>
  </form>
</li>
{%endblock%}

{% block linkBack %}
  <a class="icon-link icon-link-hover" href="{% url 'project_detail' project.pk %}">
  <- Вернуться к деталям проекта
  <svg class="bi" aria-hidden="true"><use xlink:href="#arrow-right"></use></svg>
  </a>
{% endblock %}

{% block title %}
  <h1 class="text-center">Задачи по проекту "{{project}}"</h1>
{% endblock %}

{% block filter %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Статус</h5>
    <ul class="list-group">
      {% include 'partials/status_filter.html' with list_class="list-group-item" %}
    </ul>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Дата</h5>
    <ul class="list-group">
      {% include 'partials/date_filter.html' with list_class="list-group-item"  %}
    </ul>
  </div>
</div>
{% endblock %}

{% block usersblock %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Команда проекта</h5>
    <ul class="list-group">
      {% include 'partials/user_filter.html' with list_class="list-group-item"  %}
    </ul>
  </div>
</div>
{% endblock %}

{% block content %}

{% if request.GET.search %}
  {% include 'partials/pagination_search.html' %}
{%else%}
  {% include 'partials/pagination.html' %}
{%endif%}

{% for task in tasks %}

<div class="card shadow mb-3">
  <div class="card-body">
    <h5 class="card-title">{{task.title}}</h5>
    {% include 'partials/task_status_color.html' %}
    <div class="d-flex justify-content-start">
      <p class="card-text me-2">Задача для: </p>
      {% for user in task.users.all %}
      <p class="card-text me-2">{{user}}{% if not forloop.last %}, {% endif %}</p>
      {% endfor %}
    </div>
    <p class="card-text"><small class="text-body-secondary">{{task.created_at}}</small></p>
    <a href="{% url 'task_detail' task.project.pk task.pk %}" class="btn btn-outline-primary"><i class="fa-regular fa-folder-open"></i> Открыть</a>
  </div>
</div>
{%empty%}
<h4 class="text-center">Нет задач</h4>  
{% endfor %}

{% if request.GET.search %}
  {% include 'partials/pagination_search.html' %}
{%else%}
  {% include 'partials/pagination.html' %}
{%endif%}

{% endblock %}
{% block script%}
<script src="{% static 'task_list.js' %}"></script>
{% endblock %}

templates/tasks/task_update.html
{% extends 'base.html' %}
{% block content %}


<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">Обновить задачу по проекту:</h5>
        <h5>"{{task.project}}"</h5>
        <form action="{% url 'task_update' task.project.pk task.pk %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{% url 'task_detail' task.project.pk task.pk %}" class="btn btn-outline-secondary mt-3"><i class="fa-solid fa-xmark"></i> Отмена</a>
            <button type="submit" class="btn btn-outline-primary mt-3"><i class="fa-solid fa-circle-check"></i> Изменить</button>
        </form>
    </div>
  </div>
  

{% endblock %}